import pandas as pd
from pathlib import Path


# PATH DE LOS INPUTH

PATH_INPUTS =  "datos/inputs.xlsx" 


# FECHAS

PERIODO_CONSIDERADO = pd.Timestamp('01-2025')
FECHA_PM_TTY_TBX = pd.Timestamp('01-2025') 


# CONFIG PLANTAS

FACTOR_MMm3_A_UNIDAD_VOLUMEN = 1000.0

CAPACIDAD_MEGA = 43 * FACTOR_MMm3_A_UNIDAD_VOLUMEN
CAPACIDAD_TTY_DP = 28 * FACTOR_MMm3_A_UNIDAD_VOLUMEN
CAPACIDAD_TTY_TBX = 34 * FACTOR_MMm3_A_UNIDAD_VOLUMEN
CAPACIDAD_BASE_CONVERTIBLE_TBX = 13.2 * FACTOR_MMm3_A_UNIDAD_VOLUMEN
CAPACIDAD_ADICIONAL_TBX = 20.2 * FACTOR_MMm3_A_UNIDAD_VOLUMEN
CAPACIDAD_EVACUACION_MEGA = 5600 
CAPACIDAD_EVACUACION_TTY_DP = 200 
CAPACIDAD_EVACUACION_TTY_TBX = 7700

MAX_DERIVACION_TTY_DP_A_MEGA = 5
MAX_DERIVACION_TTY_TBX_A_TTY_DP = CAPACIDAD_TTY_DP - CAPACIDAD_BASE_CONVERTIBLE_TBX



FACTOR_RETENIDOS_TTY_DP  = 1.0
FACTOR_RETENIDOS_TTY_TBX = 1.0
FACTOR_RETENIDOS_MEGA    = 1.0    # antes /1000: asumia retenidos en kg/d

# Cuantas unidades de Volumen_inyectado hay en 1 MMm3/d.
# CONFIRMAR: las capacidades de ingreso estan en MMm3/d (28, 34, 43) pero
# Volumen_inyectado viene de los inputs en otra escala.


MAX_DERIVACION_TTY_DP_A_MEGA    = 5 * FACTOR_MMm3_A_UNIDAD_VOLUMEN
MAX_DERIVACION_TTY_TBX_A_TTY_DP = (CAPACIDAD_TTY_DP - CAPACIDAD_BASE_CONVERTIBLE_TBX) * FACTOR_MMm3_A_UNIDAD_VOLUMEN

# Destinos que son plantas: solo estas rutas area->destino se rutean via HUB.
# Lo que va a gasoductos (VMN, VMS, Pampa SCH...) no se toca.
PLANTAS_VIA_HUB = ("TTY", "MEGA", "TBX El Porton")


# BOOL SAVE

GUARDAR_CSVS = True